### ISSUE TITLE
Fail to appify on windows.

### ISSUE THREAD

**Issue by mumu2001** [gzunino/tishadow-eclipse-plugin#3]
```
C:\Users\<USER>\AppData\Roaming\npm\node_modules\tishadow\node_modules\wrench\lib\wrench.js:179
        if (e.code !== 'EEXIST') throw e;
                                       ^
Error: EPERM, operation not permitted 'D:\wsp\titaniums\helloAlloyAppified'
    at Object.fs.mkdirSync (fs.js:642:18)
    at Object.exports.copyDirSyncRecursive (C:\Users\<USER>\AppData\Roaming\npm\node_modules\tishadow\node_modules\wrench\lib\wrench.js:176:12)
    at Object.exports.copyCoreProject (C:\Users\<USER>\AppData\Roaming\npm\node_modules\tishadow\cli\support\appify.js:83:12)
    at C:\Users\<USER>\AppData\Roaming\npm\node_modules\tishadow\cli\support\appify.js:112:17
    at WriteStream.<anonymous> (C:\Users\<USER>\AppData\Roaming\npm\node_modules\tishadow\cli\support\compiler.js:80:9)
    at WriteStream.EventEmitter.emit (events.js:117:20)
    at fs.js:1596:14
    at Object.oncomplete (fs.js:107:15)
```

I'm dont know to permit to create directory for tishadow plugin.

**Comment by emilianoHualpa** [comment]
Hi mumu2001. To be honest with you, we've never tested anything on windows... But seems to be a problem with the permission level of that folder. I know it could be silly but, could you try on another folder or changing the permissions?
